### ISSUE TITLE
Warning for undefined variable usage

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES#100]
I accidentally named my variable different in the source definition than in the metric and it took me a while to notice that because the LIMES console output only gave me ` ERROR org.aksw.limes.core.measures.mapper.string.PPJoinPlusPlus - Property values could not be read. Exiting
` which sounds like an input error. So I propose to give a specific error, when a variable is used in the metric that is not defined in the source or target.

**Comment by Kleanthi** [comment]
The reason you received this error is because one of your properties was null. Nothing to do with wrong variables. Also there must have been a print before the exiting message saying which property was null.
