### ISSUE TITLE
Problem in HybridCache and MemoryCache: superclass and subclass share the same field

### ISSUE THREAD

**Issue by Kleanthi** [dice-group/LIMES#106]
Both HybridCache and MemoryCache have the same field instanceMap.
HybridCache doesn't overwrite functions that deal with instanceMap in its body.

Possible error:
HybridCache c = HybridCache.loadFromFile(file); //will correctly load a cached data from a file, assuming that the data was properly cached previously
c.getInstanceMap() will return an empty map.

**Comment by MSherif** [comment]
@Kleanthi I think you fixed this, if yes please close the issue

**Comment by Kleanthi** [comment]
I have fixed it my personal branch, that is not pushed in github. The fix was quick to make things work from my side. I think the person responsible for the cache classes should look into it and do appropriate tests.

**Comment by kvndrsslr** [comment]
To be resolved by upcoming rewrite
