### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by PaulZH** [dice-group/LIMES#108]
`Exception in thread "main" java.lang.NumberFormatException: For input string: "1.0)"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.aksw.limes.core.io.parser.Parser.getTerms(Parser.java:169)
	at org.aksw.limes.core.io.parser.Parser.<init>(Parser.java:37)
	at org.aksw.limes.core.io.ls.LinkSpecification.readSpec(LinkSpecification.java:183)
	at org.aksw.limes.core.io.ls.LinkSpecification.<init>(LinkSpecification.java:72)
	at org.aksw.limes.core.controller.LSPipeline.execute(LSPipeline.java:40)
	at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:154)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:75)`

Appears after 09:19:10.906 [main] INFO  org.aksw.limes.core.io.cache.HybridCache - Serializing 150678 objects to /Applications/LIMES-dev-master/limes-core/target/cache/1714559575.ser of second triple store.

The mapping file used:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/ns/locn#</NAMESPACE>
		<LABEL>locn</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://data.vlaanderen.be/ns/adres#</NAMESPACE>
		<LABEL>add</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>CBB</ID>
		<ENDPOINT>http://rdfstoreomv-on-1.vm.cumuli.be:3030/blazegraph/namespace/cbb/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>250000</PAGESIZE>
		<RESTRICTION>?x a locn:Address</RESTRICTION>
		<PROPERTY>locn:thoroughfare AS nolang->lowercase RENAME straatnaam</PROPERTY>
		<PROPERTY>locn:locatorDesignator RENAME huisnummer</PROPERTY>
		<PROPERTY>locn:postCode RENAME postcode</PROPERTY>
		<PROPERTY>locn:postName AS nolang->lowercase RENAME gemeentenaam</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>CRAB</ID>
		<ENDPOINT>http://data.vlaanderen.be/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>250000</PAGESIZE>
		<RESTRICTION>?y a add:Adres</RESTRICTION>
		<PROPERTY>add:huisnummer RENAME huisnummer</PROPERTY>
		<PROPERTY>add:heeftStraatnaam/rdfs:label AS nolang->lowercase RENAME straatnaam</PROPERTY>
		<PROPERTY>add:heeftPostinfo/rdfs:label RENAME postcode</PROPERTY>
		<PROPERTY>add:heeftGemeentenaam/rdfs:label AS nolang->lowercase RENAME gemeentenaam</PROPERTY>
	</TARGET>
	<METRIC>AND(AND(exactmatch(y.straatnaam,x.straatnaam)|1.0,exactmatch(y.huisnummer, x.huisnummer)|1.0), exactmatch(y.gemeentenaam, x.gemeentenaam)|1.0)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>1.0</THRESHOLD>
		<FILE>mapcbb2crab.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>mapcbb2crab_near.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>

	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>

	<OUTPUT>CSV</OUTPUT>
</LIMES>
`

Command from the command line:
`java -Xms32g -Xmx32g -XX:+UseConcMarkSweepGC -jar limes-core-1.1.2.jar cbb2crab.xml `

**Comment by Kleanthi** [comment]
I assume the LS you are using is AND(AND(exactmatch(y.straatnaam,x.straatnaam)|1.0,exactmatch(y.huisnummer, x.huisnummer)|1.0), exactmatch(y.gemeentenaam, x.gemeentenaam)|1.0)

Most probably, the problem lies on the fact that you don't determine a threshold for the left child LS of your LS.

If you want to have a complex LS, each child of the LS must have its own threshold. I think you had a similar issue in the past.

So try to use:
AND(AND(exactmatch(y.straatnaam,x.straatnaam)|1.0,exactmatch(y.huisnummer, x.huisnummer)|1.0)|**1.0**), exactmatch(y.gemeentenaam, x.gemeentenaam)|1.0)

**Comment by ngonga** [comment]
AND(AND(exactmatch(y.straatnaam,x.straatnaam)|1.0,exactmatch(y.huisnummer, 
x.huisnummer)|1.0)|*1.0*, exactmatch(y.gemeentenaam, x.gemeentenaam)|1.0)


On 03/05/17 10:15, Kleanthi Georgala wrote:
> AND(AND(exactmatch(y.straatnaam,x.straatnaam)|1.0,exactmatch(y.huisnummer, 
> x.huisnummer)|1.0)|*1.0*), exactmatch(y.gemeentenaam, x.gemeentenaam)|1.0)

-- 
Axel Ngonga, Prof. Dr. rer. nat
Augustusplatz 10, Room P905
04109 Leipzig, Germany
Fon: +49(341)97-32362
