### ISSUE TITLE
needed RAM

### ISSUE THREAD

**Issue by PaulZH** [dice-group/LIMES#113]
I have on one hand as source:
- 8,5 million addresses
which I want to map to a target reference dataset containing 
- 20 million addresses.

Can I estimate in advance how much memory I need for this?
Until now I have been going to -Xmx50G but this still doesn't do the job.

The mapping file is attached.

 
[cbb2crab.xml.zip](https://github.com/dice-group/LIMES/files/1387458/cbb2crab.xml.zip)

**Comment by Kleanthi** [comment]
Hello :) It is not possible to make such estimation right now.
