### ISSUE TITLE
StringIndexOutOfBoundsException in Parser

### ISSUE THREAD

**Issue by dobraczka** [dice-group/LIMES#115]
Somebody approached me trying to use the following metric:
```
ADD(0.5* ADD(0.8* ExactMatch(a.purl:identifier, b.sg:hasPerson),0.2* Jaro(a.foaf:name, b.sg:publishedName)),0.5* ADD(0.8* ExactMatch(a.DBgridID, b.SGgridID),0.2* Jaro(a.foaf:name, b.SGgridName)))
```
This throws an `StringIndexOutOfBoundsException`. I've tracked the problem to the `getLeftCoefficient()` method in Parser: `leftTerm` is split on `\\*` therefore you get the String[] `[0.5, ADD(0.8, ExactMatch(a.purl:identifier,b.sg:hasPerson),0.2, Jaro(a.foaf:name,b.sg:publishedName))]` and leftTerm gets reassigned to `split[1]`, which turns into a problem later.
My question is now: Is this behaviour intended, meaning that the above metric is not valid? Or is this a bug?

(I've tagged Sherif, because he's the author of the Parser, but anybody else can also help)

**Comment by Kleanthi** [comment]
It is a bug indeed. There is an assumption that a complex LS with an ADD operator won't consist of other LS(s) with an ADD operator and a co-efficient.

**Comment by dobraczka** [comment]
Thanks. I guess I'll just fix it myself, since I already know how to do it.
