### ISSUE TITLE
Wombat ignores source and target variable settings of config

### ISSUE THREAD

**Issue by dobraczka** [dice-group/LIMES#117]
If I set the source and target variables in the configuration file to e.g. `?a` and `?b` Wombat will ignore this and learn metrics using `?x` and `?y` (Maybe this is intended?). This leads to problems later on in the GUI where I rely on the variable names taken from the configuration file.
I guess the best fix for this issue would be to always use the variable names from the configuration file, if they are provided. If this issue arrives somewhere else in LIMES we should address it in the same manner.

**Comment by MSherif** [comment]
Fixed
