### ISSUE TITLE
Docs: Missing docs from final book build

### ISSUE THREAD

**Issue by yamalight** [dice-group/LIMES#120]
[Final docs](http://dice-group.github.io/LIMES/user_manual/) are missing a lot of things because people forgot to add them to [SUMMARY.md](https://github.com/dice-group/LIMES/blob/master/manual/SUMMARY.md) file.
Unless your new doc file is linked in SUMMARY - it __won't__ appear in final book.
Please fix that.

**Comment by Kleanthi** [comment]
I have fixed the configuration missing parts. Please do the rest.

**Comment by mommi84** [comment]
Would a search for `*.md` files in the `user_manual/` directory tree list all the files that should be there?

**Comment by yamalight** [comment]
@mommi84 it's not just file links, it's also section headers (take a look at SUMMARY.md). if you can build a script that'd generate this kind of structure - would be cool.

**Comment by mommi84** [comment]
@yamalight yes, I meant a way to check which ones were missing.

**Comment by yamalight** [comment]
ah, yeah, sure. that should be the simplest way to check actually :)

**Comment by dobraczka** [comment]
I guess this is resolved now
