### ISSUE TITLE
How to integrate LIMES in my project

### ISSUE THREAD

**Issue by TamouzeAssi** [dice-group/LIMES#126]
Hello,

Im intersting to insert LIMES in my own application. Reading the manual i cant find how to integrate LIMES. Any help will be so appreciate
Thank you

**Comment by Kleanthi** [comment]
Hello! Thank you for taking interest in our tool. How would you like to integrate LIMES in your application? E.g. as an executable .jar?

**Comment by TamouzeAssi** [comment]
Thank you for your reply. I dont know exactly which is the best way to integrate way to integrate it. But i think the .jar wil be the best choice. pease correct me if im wrong.

I run the following command :
mvn clean package shade:shade -Dcheckstyle.skip=true -Dmaven.test.skip=true


and  I got the mentionned .jar.

But i dont know how to declare the source rdf dataset and the target, and how to execute the code to get the matching between two dataset.

Thank you in advance

**Comment by kvndrsslr** [comment]
Hello! Currently, the best way to integrate LIMES into your java application is by including the compiled jar  as a library. Having a look at `Controller.java` in package `org.aksw.limes.core.controller` together with the resources at `https://dice-group.github.io/LIMES/developer_manual/` should answer all your questions on the details. 

Another way would be to launch the compiled jar directly as you would from the command line, which could be the choice if you code in a non-JVM language.

Last but not least, there exists an option to run the executable jar as a REST web service. Note that the current implementation of the web service is rudimentary but will be improved in the future to really be a good alternative to the first approach.  

If you come up with other questions please open another issue or message us at [gitter](https://gitter.im/dice_limes/Lobby).

**Comment by judeBayd** [comment]
Sir @kvndrsslr,

Thank you. I prefered the first choice you present: exacutable .jar. I understand that i want to give a file .xml or .rdf to controller.java. This file contains the configuration like that:
<SOURCE>
    <ID>mesh</ID>
    <ENDPOINT>http://mesh.bio2rdf.org/sparql</ENDPOINT>
    <VAR>?y</VAR>
    <PAGESIZE>5000</PAGESIZE>
    <RESTRICTION>?y rdf:type meshr:Concept</RESTRICTION>
    <PROPERTY>dc:title</PROPERTY>
    <TYPE>sparql</TYPE>

Please correct me if m wrong.Thank you agin and sorry for disturbing

**Comment by judeBayd** [comment]
Thank you Sir 
@kvndrsslr 

Limes is working :)
