### ISSUE TITLE
OR on restriction property on config file 

### ISSUE THREAD

**Issue by jsaveta** [dice-group/LIMES#130]
I am trying to have a restriction in order to keep instances that are either the type of one class OR the type of a second class but if I understand correctly the restriction only allows the instance to be rdf:type of both classes. 

e.g. I want something like the following: 
<RESTRICTION>?x a something:Trace</RESTRICTION>
OR
<RESTRICTION>?x a something:Region</RESTRICTION>

and not AND.

**Comment by MSherif** [comment]
This is not supported currently in LIMES. We would enable this in a future version of LIMES. What you can do now is to extract the data you need in a single file and provide this file to LIMES as a whole.

**Comment by kvndrsslr** [comment]
Effectively a duplicate of #19 , closing this.
