### ISSUE TITLE
SparqlQueryModule: Bug for explicit URI in properties

### ISSUE THREAD

**Issue by cedricrupb** [dice-group/LIMES#135]
The `SparqlQueryModule`  resolves `?x :prop1/:prop2 ?y` to `?x :prop1 ?v1. ?v1 :prop2 ?y.`
If I choose a property with the explicit notation (like `<htttp://www.example.org/prop1>`) it will replace the slashes resulting in 
`?x <http: ?v1. ?v1 ?v2. ?v2 www.example.org ?v3. ?v3 prop1> ?y.`

**Comment by MSherif** [comment]
Currently, no explicit property notation is allowed in LIMES configuration files, instead define the prefixes to be used in the prefix section and use the prefixed version.
