### ISSUE TITLE
Insert predicat alignement direct in the configuration file

### ISSUE THREAD

**Issue by TamouzeAssi** [dice-group/LIMES#136]
Hello,

My question is not an issue but it is about the best way to do  :) I already installed and tested limes and all is ok. I want to integreate limes with my own project. My question is:

I already got the result of the alignment phase. In another word i  computed the similarity between the properties of two datasets and these properties after filtering constitute the compenent of the rule to detect the instances matching. How can transfer the alignment of properties automaticaly to be the configuration file. I dont need to rewrite manually the properties alignement found in limes, im looking a way to insert them automatically.

There is any suggested way to do that?
Thank you in advance for your help as usual :)

**Comment by Kleanthi** [comment]
It seems that the question you have is beyond the scope of our work :) 
I will go ahead and close this issue.
