### ISSUE TITLE
How to aggergate properties in the config.xml

### ISSUE THREAD

**Issue by TamouzeAssi** [dice-group/LIMES#139]
I have a question please about the configuration file.

I want to return all the instances described by three properties: p1:phone_numer + p1:age + p1:surname in file 1 and by p2:phone_numer + p2:age + p2:surname in file 2 and which are similar.

I dont know how to aggregate these properties. I do like that:
  ```
<SOURCE>
         <ID>linkedpersondata</ID>
          <ENDPOINT>C:/Users/user/data/Person/personRDF/person11.rdf</ENDPOINT>
         <VAR>?x</VAR>
         <PAGESIZE>-1</PAGESIZE>
         <RESTRICTION>?x a o1:Person</RESTRICTION>
         <PROPERTY>o1:surname</PROPERTY>
		<PROPERTY>o1:age</PROPERTY>
		<PROPERTY>o1:phone_numer</PROPERTY>
		<TYPE>RDF</TYPE>
      </SOURCE>
      <TARGET>
        <ID>linkedpersondatadata</ID>
        <ENDPOINT>C:/Users/user/data/Person/personRDF/person12.rdf</ENDPOINT>
        <VAR>?y</VAR>
        <PAGESIZE>-1</PAGESIZE>
        <RESTRICTION>?y a o2:Person</RESTRICTION>
        <PROPERTY>o2:surname</PROPERTY>
		<PROPERTY>o2:age</PROPERTY>
		<PROPERTY>o2:phone_numer</PROPERTY>
		<TYPE>RDF</TYPE>
    </TARGET>
    <METRIC>ADD(ADD(Jaccard(x.o1:surname, y.o2:surname), Jaccard(x.o1:age, y.o2:age)), Jaccard(x.o1:phone_numer, y.o2:phone_numer))</METRIC>
<ACCEPTANCE>
        <THRESHOLD>0.9</THRESHOLD>
        <FILE>C:/Users/user/Desktop/result.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </ACCEPTANCE>
    <REVIEW>
        <THRESHOLD>0.9</THRESHOLD>0
        <FILE>C:/Users/user/Desktop/resulttobereviewed.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </REVIEW>

    <EXECUTION>
        <REWRITER>default</REWRITER>
        <PLANNER>default</PLANNER>
        <ENGINE>default</ENGINE>
    </EXECUTION>

    <OUTPUT>TAB</OUTPUT>
```
but i get the following exception:

```
14:10:14.339 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:58 - Querying the endpoint.
14:10:14.339 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:64 - Getting statements 0 to -1
Exception in thread "main" org.apache.jena.query.QueryParseException: Lexical error at line 2, column 0.  Encountered: <EOF> after : "null\n"
	at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:110)
	at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
	at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
	at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
	at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:70)
	at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:40)
	at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:129)
	at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:93)
	at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:143)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:76)
	at TestDriver.main(TestDriver.java:6)
```

When I execute my code with two properties it works fine.
Any idea please where is my error?

**Comment by Kleanthi** [comment]
Hello! Thanks for using LIMES!
Couple of questions:

- Which are the two properties with whom LIMES works fine?
- Can you please attach your configuration file?

**Comment by TamouzeAssi** [comment]
[

](url)

**Comment by TamouzeAssi** [comment]
@Kleanthi please the following confi:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
    <PREFIX>
        <NAMESPACE>http://www.okkam.org/ontology_person1.owl#</NAMESPACE>
        <LABEL>o1</LABEL>
    </PREFIX>
    <PREFIX>
        <NAMESPACE>http://www.okkam.org/ontology_person2.owl#</NAMESPACE>
        <LABEL>o2</LABEL>
    </PREFIX>
    <PREFIX>
        <NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
        <LABEL>owl</LABEL>
    </PREFIX>
	
    <SOURCE>
        <ID>linkedpersondata</ID>
        <ENDPOINT>C:/Users/user/data/Person/personRDF/p1.rdf</ENDPOINT>
        <VAR>?x</VAR>
        <PAGESIZE>-1</PAGESIZE>
        <RESTRICTION>?x a o1:Person</RESTRICTION>
        <PROPERTY>o1:given_name</PROPERTY>
		<PROPERTY>o1:surname</PROPERTY>
		<TYPE>RDF</TYPE>
    </SOURCE>
    <TARGET>
        <ID>linkedpersondatadata</ID>
        <ENDPOINT>C:/Users/user/data/Person/personRDF/person12.rdf</ENDPOINT>
        <VAR>?y</VAR>
        <PAGESIZE>-1</PAGESIZE>
        <RESTRICTION>?y a o2:Person</RESTRICTION>
        <PROPERTY>o2:given_name</PROPERTY>
		<PROPERTY>o2:surname</PROPERTY>
		<TYPE>RDF</TYPE>
    </TARGET>
    <METRIC>ADD(Jaccard(x.o1:given_name, y.o2:given_name), Jaccard(x.o1:sruname, y.o2:surname))</METRIC>
    <ACCEPTANCE>
        <THRESHOLD>0.9</THRESHOLD>
        <FILE>C:/Users/user/Desktop/result.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </ACCEPTANCE>
    <REVIEW>
        <THRESHOLD>0.9</THRESHOLD>
        <FILE>C:/Users/user/Desktop/resulttobereviewed.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </REVIEW>

    <EXECUTION>
        <REWRITER>default</REWRITER>
        <PLANNER>default</PLANNER>
        <ENGINE>default</ENGINE>
    </EXECUTION>

    <OUTPUT>TAB</OUTPUT>
</LIMES>`

The result i get is : 
`2018-02-15 19:36:50,942 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-02-15 19:36:50,954 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-02-15 19:36:51,110 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-02-15 19:36:51,111 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
19:36:51.181 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file C:\Users\user\workspaceMarsNEW\TestLimes\cache\831483914.ser
19:36:51.183 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\831483914.ser
19:36:51.393 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\831483914.ser
19:36:51.394 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 358
19:36:51.394 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file C:\Users\user\workspaceMarsNEW\TestLimes\cache\380726829.ser
19:36:51.395 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\380726829.ser
19:36:51.548 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\380726829.ser
19:36:51.548 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 500
19:36:51.712 [main] INFO  org.aksw.limes.core.controller.Controller:166 - Mapping task finished in 160 ms
19:36:51.713 [main] INFO  org.aksw.limes.core.controller.Controller:170 - Mapping size: 0 (accepted) + 0 (need verification) = 0 (total)
19:36:51.716 [main] INFO  org.aksw.limes.core.io.serializer.SerializerFactory:15 - Getting serializer with name TAB
`

Note that i have 358 instances in dataset p1 which has surname + given_name. I dont know why i get 0 accepted instances. 

By the way can you please correct me where is my bug? For me surname+given_name is my logic rule to match the instances p1 to person2.rdf. 

In addition, can you please tell me how to aggregate three properties?
Thank you

**Comment by Kleanthi** [comment]
First of all, please read the instructions here in our user manual on how to write a correct atomic or complex LS: http://dice-group.github.io/LIMES/user_manual/configuration_file/metric/
Based on what I see in your configuration file, the thresholds of your atomic LSs within your metric are missing. 
Second, please read the instructions here on how to define the prefixes of your data: http://dice-group.github.io/LIMES/user_manual/configuration_file/prefixes.html

After you have fixed the above, I will suggest to delete the cached files from your system and try to run LIMES again first with jaccard. Then check if you still get 0 links in the mappings. From what I see, you have set the threshold quite high and there is a chance that most pairs are rejected. Try to use a lower threshold. Also please check your files to see if you actually have pairs that could be matched. 

Once you've done this, delete the cached files again and then re-run LIMES using exact match.

**Comment by Kleanthi** [comment]
I have fixed a small bug regarding the ADD operator. Please use our final release with tag 1.2.2

**Comment by TamouzeAssi** [comment]
@Kleanthi thank you but i already defined well the prefix but i dont show it in th above message.
I tried to delete the cach, and i test with only one property and i set the acceptance threshold very low = 0.01
1- With exactMatch i have the same exceptiom
2- with jaccard, levein. no excetion and the xecution is very good.

Bu the way, im little bit confused, can u mention please the link on the new realase.

**Comment by Kleanthi** [comment]
The new release is under the Release tab in our project.

So with jaccard and a low threshold, you receive a mapping? If that is the case, then the string similarity works fine, your data doesn't seem to have a lot of pairs with high similarity.

Please try exacth match with the new release.

**Comment by TamouzeAssi** [comment]
With jaccard even if the threshold is 0.95 i get results

**Comment by Kleanthi** [comment]
ok, good to know. Any other questions left?

**Comment by TamouzeAssi** [comment]
After getting the new released. When you run the following mteric:
ADD(0.5*Jaccard(x.o1:soc_sec_id, y.o2:soc_sec_id)|0.01, 0.5*Jaccard(x.o1:surname, y.o2:surname)|0.01)

we get results in the mentionned result file but we have the following exception:
`14:26:28.832 [main] WARN  org.aksw.limes.core.io.config.reader.xml.XMLConfigurationReader:418 - multiple points
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.aksw.limes.core.io.config.reader.xml.XMLConfigurationReader.validateAndRead(XMLConfigurationReader.java:374)
	at org.aksw.limes.core.io.config.reader.xml.XMLConfigurationReader.read(XMLConfigurationReader.java:197)
	at org.aksw.limes.core.controller.Controller.getConfig(Controller.java:125)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:75)
	at TestDriver.main(TestDriver.java:6)
14:26:28.835 [main] WARN  org.aksw.limes.core.io.config.reader.xml.XMLConfigurationReader:420 - Some values were not set. Crossing my fingers and using defaults.
14:26:28.838 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-767435754.ser
14:26:28.838 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-767435754.ser
14:26:29.017 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-767435754.ser
14:26:29.017 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 360
14:26:29.018 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-1218192839.ser
14:26:29.018 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-1218192839.ser
14:26:29.139 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-1218192839.ser
14:26:29.140 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 500
14:26:29.304 [main] INFO  org.aksw.limes.core.controller.Controller:166 - Mapping task finished in 160 ms
14:26:29.307 [main] INFO  org.aksw.limes.core.controller.Controller:170 - Mapping size: 284 (accepted) + 0 (need verification) = 284 (total)
14:26:29.310 [main] INFO  org.aksw.limes.core.io.serializer.SerializerFactory:15 - Getting serializer with name null
14:26:29.313 [main] WARN  org.aksw.limes.core.io.serializer.NtSerializer:166 - Error creating PrintWriter
14:26:29.313 [main] WARN  org.aksw.limes.core.io.serializer.NtSerializer:167 - null
java.lang.NullPointerException
	at org.aksw.limes.core.io.serializer.NtSerializer.open(NtSerializer.java:159)
	at org.aksw.limes.core.io.serializer.NtSerializer.writeToFile(NtSerializer.java:83)
	at org.aksw.limes.core.controller.Controller.writeResults(Controller.java:179)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:77)
	at TestDriver.main(TestDriver.java:6)
14:26:29.314 [main] WARN  org.aksw.limes.core.io.serializer.NtSerializer:149 - Error closing PrintWriter
14:26:29.314 [main] WARN  org.aksw.limes.core.io.serializer.NtSerializer:150 - null`

With the one metric exactMatch, error stil presenting:
`<METRIC>ExactMatch(x.o1:soc_sec_id, y.o2:soc_sec_id)</METRIC>
    <ACCEPTANCE>
        <THRESHOLD>0.01/THRESHOLD>
        <FILE>C:/Users/user/Desktop/result.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </ACCEPTANCE>
    <REVIEW>
        <THRESHOLD>0.01</THRESHOLD>
        <FILE>C:/Users/user/Desktop/resulttobereviewed.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </REVIEW>`

`14:28:01.221 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:58 - Querying the endpoint.
14:28:01.221 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:64 - Getting statements 0 to -1
Exception in thread "main" org.apache.jena.query.QueryParseException: Lexical error at line 2, column 0.  Encountered: <EOF> after : "null\n"
	at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:110)
	at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
	at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
	at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
	at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:70)
	at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:40)
	at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:129)
	at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:93)
	at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:143)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:76)
	at TestDriver.main(TestDriver.java:6)`

error stil present

**Comment by TamouzeAssi** [comment]
With ExactMatch, the full log is:
`14:37:59.216 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-1678371901.ser
14:37:59.218 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-1678371901.ser
14:37:59.383 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file C:\Users\user\workspaceMarsNEW\TestLimes\cache\-1678371901.ser
14:37:59.383 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 424
14:37:59.383 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file C:\Users\user\workspaceMarsNEW\TestLimes\cache\1949679235.ser
14:37:59.384 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:127 - No cached data found for linkedpersondatadata
14:37:59.385 [main] INFO  org.aksw.limes.core.io.query.QueryModuleFactory:18 - Generating <RDF> reader
Trying to get reader RDF/XML
14:38:00.035 [main] WARN  org.apache.jena.riot:77 - [line: 1, col: 46] {W129} Encoding on InputStreamReader or FileReader does not match that of XML document. Use FileInputStream. [UTF-8 != windows-1252]
14:38:00.589 [main] INFO  org.aksw.limes.core.io.query.FileQueryModule:52 - here
14:38:00.590 [main] INFO  org.aksw.limes.core.io.query.FileQueryModule:53 - RDF model read from C:/Users/user/data/Person/personRDF/person12.rdf is of size 7000
14:38:00.592 [main] INFO  LIMES:32 - Registry = [C:/Users/user/data/Person/personRDF/person12.rdf]
14:38:00.595 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:245 - Query issued is 
PREFIX o1: <http://www.okkam.org/ontology_person1.owl#>
PREFIX o2: <http://www.okkam.org/ontology_person2.owl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?y ?v0
WHERE {
?y a o2:Person .
?y o2:soc_sec_id ?v0 .
}
14:38:00.596 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:58 - Querying the endpoint.
14:38:00.596 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:64 - Getting statements 0 to -1
14:38:01.069 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:153 - Retrieved 500 triples and 500 entities.
14:38:01.069 [main] INFO  org.aksw.limes.core.io.query.SparqlQueryModule:154 - Retrieving statements took 0.474 seconds.
14:38:01.070 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:304 - Serializing 500 objects to C:\Users\user\workspaceMarsNEW\TestLimes\cache\1949679235.ser
Exception in thread "main" java.lang.NullPointerException
	at org.aksw.limes.core.measures.mapper.string.ExactMatchMapper.lambda$getMapping$0(ExactMatchMapper.java:63)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.aksw.limes.core.measures.mapper.string.ExactMatchMapper.getMapping(ExactMatchMapper.java:61)
	at org.aksw.limes.core.execution.engine.SimpleExecutionEngine.executeRun(SimpleExecutionEngine.java:171)
	at org.aksw.limes.core.execution.engine.SimpleExecutionEngine.executeInstructions(SimpleExecutionEngine.java:87)
	at org.aksw.limes.core.execution.engine.SimpleExecutionEngine.executeStatic(SimpleExecutionEngine.java:284)
	at org.aksw.limes.core.execution.engine.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:492)
	at org.aksw.limes.core.controller.LSPipeline.execute(LSPipeline.java:73)
	at org.aksw.limes.core.controller.LSPipeline.execute(LSPipeline.java:41)
	at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:160)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:76)
	at TestDriver.main(TestDriver.java:6)`

**Comment by Kleanthi** [comment]
Regarding your first error with Jaccard, please read again **carefully** the manual regarding the construction of a LS.
I am trying to find an answer for your 2nd error.

**Comment by TamouzeAssi** [comment]
Im sorry but i dont know woth the star is not appearing in: 
`ADD(0.5*Jaccard(x.o1:soc_sec_id, y.o2:soc_sec_id)|0.01, 0.5*Jaccard(x.o1:surname, y.o2:surname)|0.01)`

**Comment by Kleanthi** [comment]
Which java version are you using?

**Comment by TamouzeAssi** [comment]
java 1.8.0_91

**Comment by Kleanthi** [comment]
I manage to reproduce your first error by doing the following:

<REVIEW>
		**<THRESHOLD>0.1.9</THRESHOLD>**
		<FILE>lgd_relaybox_near.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</REVIEW>

are you sure you don't have an extra dot somewhere in your threshold?

**Comment by TamouzeAssi** [comment]
For the add it is ok now. But Please help in solving the exactMatch problem:
`<METRIC>ExactMatch(x.o1:soc_sec_id, y.o2:soc_sec_id)</METRIC>
    <ACCEPTANCE>
        <THRESHOLD>0.001</THRESHOLD>
        <FILE>C:/Users/user/Desktop/result.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </ACCEPTANCE>
    <REVIEW>
        <THRESHOLD>0.001</THRESHOLD>
        <FILE>C:/Users/user/Desktop/resulttobereviewed.tsv</FILE>
        <RELATION>owl:sameAs</RELATION>
    </REVIEW>
`

**Comment by Kleanthi** [comment]
My suggestion is that you create a zip and you put inside the 2 source files and your configuration.
Then I will run it in my laptop and check if I can reproduce the error.

**Comment by TamouzeAssi** [comment]
[TobeTested.zip](https://github.com/dice-group/LIMES/files/1732758/TobeTested.zip)

**Comment by TamouzeAssi** [comment]
@Kleanthi i attached the file. Thank you so much im really appreaciated

**Comment by Kleanthi** [comment]
So I managed to reproduce your error locally.
First, please change the type tag of your target to N3.
Secondly, we found the bug and fixed it. We will upload a new version of LIMES shortly.

**Comment by TamouzeAssi** [comment]
@Kleanth, sorry for this work before the week-end. I will wait the new release

**Comment by Kleanthi** [comment]
No worries, happy to help. I will let you know when things are ready :)

**Comment by Kleanthi** [comment]
https://github.com/dice-group/LIMES/releases/tag/1.2.3
Here is the new release, in which we fixed the bug for the exact match.

**Comment by TamouzeAssi** [comment]
@Kleanthi sorry but still a small bug with the exactMatch metric. look please:

with jaccard and other metrics is the result is as we want, and it is the form:
`<http://www.okkam.org/oaie/person1-Person4450>	<http://www.okkam.org/oaie/person2-Person4451>	1.0`

But with ExactMatch the result is true but the swap the place of source and target. the result looks like:
`<http://www.okkam.org/oaie/person2-Person4451>	<http://www.okkam.org/oaie/person1-Person4450>	1.0`

**Comment by kvndrsslr** [comment]
@TamouzeAssi Hello, I will have a look at this shortly. Thanks for reporting!
