### ISSUE TITLE
Comparing 2 instances with exactMatch

### ISSUE THREAD

**Issue by BilalKoteich** [dice-group/LIMES#159]
If i want to make an alignment between two instances (two strings) with exactMatch, what value should I set for the threshold? and why do we need the threshold in this case? we specify a threshold in case we want to determine the degree of similarity in order to choose the results.

Thanks in advance !

**Comment by Kleanthi** [comment]
Hey, thanks for your interest in LIMES.
There is a difference between the concept of the exact match similarity and its implementantion.
Based on the theory behind the similarity, two strings either similar or not, which is quite straight-forward and does not require a threshold.
However implementation-wise, each similarity and its corresponding mapper must extend and/or implement particular superclass and interfaces that require a threshold to be present.
If you run an experiment with threshold = 1 and a threshold != 1 (>0) you will see that the results you get are the same.
