### ISSUE TITLE
[WebUI] Implement proper METRIC field parsing

### ISSUE THREAD

**Issue by kvndrsslr-zz** [dice-group/LIMES#164]
Right now, the metric input element allows multiple metric declarations which all get rendered into their own <METRIC> xml tag.
However, LIMES supports only one <METRIC> tag and atomic measures need to be combined with combine operators to form complex link specifications.
Two ways to solve this:
1. (easy) restrict input field to only accept one metric string
2. (harder but more user friendly) provide nice interface to assemble link specifications from declared property names using a list of available measures and operators. (mimic the desktop GUI)

**Comment by kvndrsslr** [comment]
Fixed in #d9b14c0
