### ISSUE TITLE
Improve usability of "new configuration" in LIMES GUI

### ISSUE THREAD

**Issue by ironjan** [dice-group/LIMES#166]
When setting up a new configuration according to the [user manual](http://dice-group.github.io/LIMES/user_manual/gui/new_config/create_new_config.html), it is mentioned that `-1` means `fetch all pages`:

> Page size: How many pages of the endpoint should be fetched? (-1 = all)

However, users (like me), tend to overlook things like this and just stick with the default value which seems dangerous in this case. When I used LIMES to test some things, I always ended up receiving `HTTP 500` after some time.

Therefor I'd propose to change the value to something more sensible (perhaps 1000?). 

Another approach would be to only allow positive numbers in "page size" and add a checkbox "fetch all pages" (checkbox enabled <-> text input disabled). That way users can explicitly choose to download all pages instead of implicitly choosing.

**Comment by Kleanthi** [comment]
I don't agree with the argument that users overlook the manual. This shouldn't be a reason to change things in LIMES. Unless it is something that is not explained well, we can either fix the description in the manual or fix the code.
We spend a lot of time writing it and reviewing it to make sure everything is clear.
If others agree, you can go ahead and change it.

**Comment by kvndrsslr** [comment]
GUI discontinued, closing this.
