### ISSUE TITLE
DataSetChooser is not extendable or usable outside of LIMES

### ISSUE THREAD

**Issue by cedricrupb** [dice-group/LIMES#168]
The current version prohibits the use of DataSetChooser outside of LIMES caused by:

1. All methods are static --> no superclass or override is possible
2. Enum MapKey is private --> build evaluationData by hashMap is not possible
3. All paths are relative to project hierarchy --> If the project is compiled as jar we won't be able to load any dataset

The only way to extend the datasets is to create an EvaluationData object by hand and make use of the setter (But it won't solve point 3)

In the branch "features/new-graph-similarity-measure" I added DataSetChooser2 (WIP) [>>LINK<<](https://github.com/dice-group/LIMES/tree/feature/new-graph-similarity-measure/limes-core/src/main/java/org/aksw/limes/core/evaluation/evaluationDataLoader).
It reimplements the DataSetChooser in a more OOP fashion. Therefore it is easy to extend when you want to use LIMES as a dependency or within. Moreover I auto-resolve path. So dataset files can be loaded both in development and production.

**Comment by kvndrsslr** [comment]
Thanks, I'll consider including this in the next major release.
