### ISSUE TITLE
The docker is not running, help

### ISSUE THREAD

**Issue by jtrillos** [dice-group/LIMES#169]
Hi I am trying to use the dockerfile but when I run it it shows
`13:10:59.040 [main] INFO  org.aksw.limes.core.controller.SimpleServer:44 - Attempting to start LIMES server at port 8080...
13:10:59.151 [main] INFO  org.aksw.limes.core.controller.SimpleServer:56 - Server has been started! Waiting for requests...
`
Can someone help me?

**Comment by Kleanthi** [comment]
Hello! Thank you for your interest in LIMES.
Please read the manual before using out tool. Most components include examples to familiarize yourself with LIMES.
http://dice-group.github.io/LIMES/user_manual/server/overview.html
