### ISSUE TITLE
Is there a way to use csv datasets?

### ISSUE THREAD

**Issue by jtrillos** [dice-group/LIMES#172]
Hi,
I have a question, is there a possibility to use a csv dataset in Limes? I read the [user manual](http://dice-group.github.io/LIMES/user_manual/configuration_file/data_sources.html) but I did not understand.

Can you help me?

Thanks

**Comment by kvndrsslr** [comment]
Hello, it should be pretty obvious from the user manual

> In addition, a source type can be set via TYPE. The default type is set to SPARQL (for a SPARQL endpoint) but LIMES also supports reading files directly from the hard-drive. The supported data formats are
> 
> - CSV: Character-separated file can be loaded directly into LIMES. Note that the separation character is set to TAB as a default. The user can alter this setting programmatically.
> - N3 (which also reads NT files) reads files in the N3 language.
> - N-TRIPLE reads files in W3C's core N-Triples format
> - TURTLE allows reading files in the Turtle syntax.

and 

> The endpoint of the data source needs to be explicated via the ENDPOINT tag.
>  - If the data is to be queried from a SPARQL end point, the ENDPOINT tag must be set to the corresponding SPARQL endpoint URI.
>  - In case the data is stored in a local file (CSV, N3, TURTLE, etc.), ENDPOINT tag must be set to the absolute path of the file containing the data.

So all you have to do is set the `<TYPE>` element to `CSV` and `<ENDPOINT>` to the path of your file.
