### ISSUE TITLE
Question: how to use the 'concat' function in dev branch ?

### ISSUE THREAD

**Issue by BilalKoteich** [dice-group/LIMES#173]
Hi.
I am using the dev branch, because i want to do a concatenation using the preprocessing function 'concat'.
So how to use it in the config file ? for exemple i want to concatenate 'skos:prefLabel' to 'skos:editorialNote'.

Thanks in advance !

**Comment by kvndrsslr** [comment]
Hello, if you're using the dev branch, it might be beneficial to read the manual in the dev branch.
https://github.com/dice-group/LIMES/blob/dev/manual/user_manual/configuration_file/data_sources.md
