### ISSUE TITLE
Error when I do mvn install

### ISSUE THREAD

**Issue by jtrillos** [dice-group/LIMES#178]
I clone the github repository and i did the mvn clean install and appear 100 errors. The errors are in LIMES GUI. Can you help me?

`[INFO] 100 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] LIMES .............................................. SUCCESS [  3.847 s]
[INFO] LIMES .............................................. SUCCESS [22:18 min]
[INFO] LIMES GUI .......................................... FAILURE [  2.912 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22:25 min
[INFO] Finished at: 2018-07-03T19:39:07+02:00
[INFO] Final Memory: 52M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project limes-gui: Compilation failure: Compilation failure: 
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[5,29] package javafx.beans.property does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[6,29] package javafx.beans.property does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[7,29] package javafx.beans.property does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[8,29] package javafx.beans.property does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[9,23] package javafx.geometry does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[10,20] package javafx.scene does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[11,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[12,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[13,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[14,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[15,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[16,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[17,26] package javafx.scene.paint does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[18,20] package javafx.stage does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[27,13] cannot find symbol
[ERROR]   symbol:   class Stage
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/TaskProgressController.java:[11,25] package javafx.concurrent does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[32,13] cannot find symbol
[ERROR]   symbol:   class StringProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[33,13] cannot find symbol
[ERROR]   symbol:   class ProgressBar
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[34,13] cannot find symbol
[ERROR]   symbol:   class BooleanProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[35,13] cannot find symbol
[ERROR]   symbol:   class BooleanProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[113,12] cannot find symbol
[ERROR]   symbol:   class StringProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[121,12] cannot find symbol
[ERROR]   symbol:   class ProgressBar
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[125,12] cannot find symbol
[ERROR]   symbol:   class BooleanProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/TaskProgressView.java:[133,12] cannot find symbol
[ERROR]   symbol:   class BooleanProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.TaskProgressView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/TaskProgressController.java:[35,17] cannot find symbol
[ERROR]   symbol:   class Task
[ERROR]   location: class org.aksw.limes.core.gui.controller.TaskProgressController
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/TaskProgressController.java:[43,35] cannot find symbol
[ERROR]   symbol:   class Task
[ERROR]   location: class org.aksw.limes.core.gui.controller.TaskProgressController
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/TaskProgressController.java:[64,29] cannot find symbol
[ERROR]   symbol:   class Task
[ERROR]   location: class org.aksw.limes.core.gui.controller.TaskProgressController
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/ClassMatchingTreeCell.java:[5,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/ClassMatchingTreeCell.java:[6,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/ClassMatchingTreeCell.java:[14,44] cannot find symbol
[ERROR]   symbol: class TreeCell
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[15,28] package javafx.beans.binding does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[16,29] package javafx.beans.property does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[17,29] package javafx.beans.property does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[18,26] package javafx.beans.value does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[19,26] package javafx.beans.value does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[20,26] package javafx.collections does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[21,20] package javafx.event does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[22,20] package javafx.event does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[23,23] package javafx.geometry does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[24,20] package javafx.scene does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[25,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[26,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[27,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[28,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[29,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[30,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[31,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[32,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[33,33] package javafx.scene.control.cell does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[34,26] package javafx.scene.input does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[35,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[36,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[37,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[38,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[39,26] package javafx.scene.paint does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/IEditView.java:[3,20] package javafx.scene does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/EditClassMatchingController.java:[16,26] package javafx.scene.paint does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[53,17] cannot find symbol
[ERROR]   symbol:   class ScrollPane
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[5,20] package javafx.scene does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[6,20] package javafx.scene does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[7,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[8,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[9,27] package javafx.scene.layout does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[10,20] package javafx.stage does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[59,17] cannot find symbol
[ERROR]   symbol:   class Button
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[64,17] cannot find symbol
[ERROR]   symbol:   class BooleanProperty
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[67,17] cannot find symbol
[ERROR]   symbol:   class TreeView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[68,17] cannot find symbol
[ERROR]   symbol:   class TreeView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[69,17] cannot find symbol
[ERROR]   symbol:   class Label
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[70,17] cannot find symbol
[ERROR]   symbol:   class TitledPane
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[71,17] cannot find symbol
[ERROR]   symbol:   class TitledPane
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[74,17] cannot find symbol
[ERROR]   symbol:   class TableView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[75,17] cannot find symbol
[ERROR]   symbol:   class Label
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[101,17] cannot find symbol
[ERROR]   symbol:   class Parent
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[158,17] cannot find symbol
[ERROR]   symbol:   class ScrollPane
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[189,17] cannot find symbol
[ERROR]   symbol:   class ScrollPane
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[213,17] cannot find symbol
[ERROR]   symbol:   class TableView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[234,16] cannot find symbol
[ERROR]   symbol:   class Parent
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[244,17] cannot find symbol
[ERROR]   symbol:   class TitledPane
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[269,38] cannot find symbol
[ERROR]   symbol:   class TreeItem
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[302,31] cannot find symbol
[ERROR]   symbol:   class ObservableList
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[331,16] cannot find symbol
[ERROR]   symbol:   class TreeView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[335,16] cannot find symbol
[ERROR]   symbol:   class TreeView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[339,16] cannot find symbol
[ERROR]   symbol:   class TableView
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[343,16] cannot find symbol
[ERROR]   symbol:   class Label
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[347,16] cannot find symbol
[ERROR]   symbol:   class Label
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/EditClassMatchingView.java:[351,16] cannot find symbol
[ERROR]   symbol:   class Button
[ERROR]   location: class org.aksw.limes.core.gui.view.EditClassMatchingView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/IEditView.java:[29,12] cannot find symbol
[ERROR]   symbol:   class Parent
[ERROR]   location: interface org.aksw.limes.core.gui.view.IEditView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/model/Config.java:[37,26] package javafx.collections does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/model/Config.java:[38,25] package javafx.concurrent does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/model/Config.java:[39,28] package javafx.scene.control does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/model/Config.java:[40,34] package javafx.scene.control.Alert does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/WizardController.java:[10,26] package javafx.beans.value does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/controller/WizardController.java:[11,26] package javafx.beans.value does not exist
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[20,13] cannot find symbol
[ERROR]   symbol:   class Button
[ERROR]   location: class org.aksw.limes.core.gui.view.WizardView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[21,13] cannot find symbol
[ERROR]   symbol:   class Button
[ERROR]   location: class org.aksw.limes.core.gui.view.WizardView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[22,13] cannot find symbol
[ERROR]   symbol:   class BorderPane
[ERROR]   location: class org.aksw.limes.core.gui.view.WizardView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[23,13] cannot find symbol
[ERROR]   symbol:   class Stage
[ERROR]   location: class org.aksw.limes.core.gui.view.WizardView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[91,12] cannot find symbol
[ERROR]   symbol:   class Stage
[ERROR]   location: class org.aksw.limes.core.gui.view.WizardView
[ERROR] /home/jaimetrillos/Documents/Github_BigDataOcean/LIMES/limes-gui/src/main/java/org/aksw/limes/core/gui/view/WizardView.java:[95,31] cannot find symbol
[ERROR]   symbol:   class Parent
[ERROR]   location: class org.aksw.limes.core.gui.view.WizardView
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :limes-gui`

**Comment by Kleanthi** [comment]
Hello.
Please try to run the mvn command in the limes-core folder not the limes-gui folder.

**Comment by kvndrsslr** [comment]
Hello,
it does seem you are using java 10. LIMES (GUI) does not support java 10 currently.
Please use java 8 or 9 instead to build or alternatively use the artifacts supplied with the official LIMES releases here on github.
