### ISSUE TITLE
Problem with use weight

### ISSUE THREAD

**Issue by cz279708573** [dice-group/LIMES#179]
Hello:
I used the LIMES-core version 1.4.0
when i used
```
ADD(0.3 * Levenshtein(x.BirthYM, y.BirthYM) |0.3, 0.7 * Levenshtein(x.LeaderName, y.LeaderName)|0.7 )
```
as metric, it doesn't work.
my acceptance threshold is 0.9 and my review threshold  is 0.1.
I debug find in LinkSpecification.class's Method readSpec, it has next code:

```java
else if (p.getOperator().equalsIgnoreCase("ADD")) {
    this.setOperator(LogicOperator.AND);
    leftSpec.readSpec(p.getLeftTerm(), Math.abs(theta - p.getRightCoefficient()) / p.getLeftCoefficient());
    rightSpec.readSpec(p.getRightTerm(), Math.abs(theta - p.getLeftCoefficient()) / p.getRightCoefficient());
    this.filterExpression = null;
    this.setThreshold(theta);
    this.fullExpression = "AND(" + leftSpec.fullExpression + "|" + Math.abs(theta - p.getRightCoefficient()) / p.getLeftCoefficient() + "," + rightSpec.fullExpression + "|" + Math.abs(theta - p.getLeftCoefficient()) / p.getRightCoefficient() + ")";
}
leftSpec.readSpec(p.getLeftTerm(), Math.abs(theta - p.getRightCoefficient()) / p.getLeftCoefficient());
```
this code will set the leftSpec's  threshold to 2.0 （abc(0.1-0.7)/0.3 = 2  ）

and it,s wrong when execute in EDJoinMapper.class because next code:

```java
threshold = (1.0D - threshold) / threshold;
this.comparisons = 0;
mapping = MappingFactory.createDefaultMapping();
if (threshold < 0.0D) {
    logger.info("Wrong threshold setting. Returning empty mapping.");
    return mapping;
} 
```

**Comment by kvndrsslr** [comment]
Thanks for reporting this. We will be looking into it shortly!

**Comment by cz279708573** [comment]
A：
sub expression have coefficient but no threshold
a1 * Levenshtein(x.BirthYM, y.BirthYM), a2 * Levenshtein(x.LeaderName, y.LeaderName)
set   Levenshtein(x.BirthYM, y.BirthYM)  as x, Levenshtein(x.LeaderName, y.LeaderName) as y 
threshold  z
a1 * x + a2 * y > z
x > ( z- a2 * y ) / a1 ,
we want get the min x , set y = 1 
=>   x > ( z- a2  ) / a1 ,
**when z > a2 **
so，have the next code , it's right , 
`leftSpec.readSpec(p.getLeftTerm(), Math.abs(theta - p.getRightCoefficient()) / p.getLeftCoefficient());`
but if **z <= a2** ,  ( z- a2  ) / a1 < 0,  may be we should have next code:
`leftSpec.readSpec(p.getLeftTerm(),  x );`
x could be any Double data bigger than 0.

B：
sub expression have coefficient but no threshold
a1 * Levenshtein(x.BirthYM, y.BirthYM) | b1 , a2 * Levenshtein(x.LeaderName, y.LeaderName) | b2
threshold  z
a1 * x + a2 * y > z
x > b1 , y > b2
x =  ( z- a2 * y ) / a1
thers have  3 case: 
1、 z > a2, x >  (z - a2) / a1 , (z - a2) / a1 >b1
      sub expression x  threshold should be (z - a2) / a1
2、 z > a2, x >  (z - a2) / a1 , (z - a2) / a1 < b1
      sub expression x  threshold should be b1
3、 z < a2 , x >  (z - a2) / a1 ,  (z-a2) / a1 < 0  , but b1>0  , so b1>(z-a2) / a1
      sub expression x  threshold should be b1
