### ISSUE TITLE
Issue in sparql Endpoint

### ISSUE THREAD

**Issue by 90arslan** [dice-group/LIMES#183]
I'm trying to interlink Wikidata and Openaire SPARQL endpoints. In Limes version 1.0 the wiki data endpoint https://query.wikidata.org/sparql?force=true  works but when I use the same config file in 1.5 version it gives an error 

11:18:46.548 [main] [] WARN  org.apache.http.client.protocol.ResponseProcessCookies:130 - Invalid cookie header: "Set-Cookie: WMF-Last-Access=03-Sep-2018;Path=/;HttpOnly;secure;Expires=Fri, 05 Oct 2018 00:00:00 GMT". Invalid 'expires' attribute: Fri, 05 Oct 2018 00:00:00 GMT
11:18:46.549 [main] [] WARN  org.apache.http.client.protocol.ResponseProcessCookies:130 - Invalid cookie header: "Set-Cookie: WMF-Last-Access-Global=03-Sep-2018;Path=/;Domain=.wikidata.org;HttpOnly;secure;Expires=Fri, 05 Oct 2018 00:00:00 GMT". Invalid 'expires' attribute: Fri, 05 Oct 2018 00:00:00 GMT

**Comment by Kleanthi** [comment]
Hey there! Can you please attach your config file to see if we can reproduce the error?

**Comment by 90arslan** [comment]
Sorry, yes it's warning but it did not retrieved data in version 1.5. but this file retrieved data in 1.0



<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>

	<PREFIX>
        <NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
        <LABEL>foaf</LABEL>
    </PREFIX>
    <PREFIX>
        <NAMESPACE>http://lod.openaire.eu/vocab/</NAMESPACE>
        <LABEL>oav</LABEL>
    </PREFIX>
	<PREFIX>
        <NAMESPACE>http://dbpedia.org/property/</NAMESPACE>
        <LABEL>dbp</LABEL>
    </PREFIX>
	<PREFIX>
        <NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
        <LABEL>rdf</LABEL>
    </PREFIX>
		<PREFIX>
        <NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
        <LABEL>owl</LABEL>
    </PREFIX>
	 
	<PREFIX>
        <NAMESPACE>http://wikiba.se/ontology#</NAMESPACE>
        <LABEL>wikibase</LABEL>
    </PREFIX>
	<PREFIX>
        <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
        <LABEL>rdfs</LABEL>
    </PREFIX>
	
	<PREFIX>
        <NAMESPACE>http://purl.org/dc/terms/</NAMESPACE>
        <LABEL>dcterms</LABEL>
    </PREFIX>
	<PREFIX>
        <NAMESPACE>http://wikiba.se/ontology#</NAMESPACE>
        <LABEL>wikibase</LABEL>
    </PREFIX>
	<PREFIX>
        <NAMESPACE>http://www.wikidata.org/prop/direct/</NAMESPACE>
        <LABEL>wdt</LABEL>
    </PREFIX>

	<PREFIX>
        <NAMESPACE>http://www.aktors.org/ontology/portal#</NAMESPACE>
        <LABEL>akt</LABEL>
    </PREFIX>

	
<SOURCE>
        <ID>openaire</ID>
        <ENDPOINT>http://lod.openaire.eu/sparql/</ENDPOINT>
        <VAR>?x</VAR>
        <PAGESIZE>1000</PAGESIZE>
	<MAXOFFSET>1000</MAXOFFSET>
        <RESTRICTION>?x oav:resultType 'publication'</RESTRICTION>
        <PROPERTY>oav:title AS lowercase RENAME title</PROPERTY>

</SOURCE>
<TARGET>
        <ID>wikidata</ID>
        <ENDPOINT>https://query.wikidata.org/sparql?force=true</ENDPOINT>
        <VAR>?y</VAR>
        <PAGESIZE>1000</PAGESIZE>
	<MAXOFFSET>10000</MAXOFFSET>
        <RESTRICTION>?y ?p 'wd:Q732577'</RESTRICTION>
        <PROPERTY>wdt:P1476 AS lowercase RENAME title2</PROPERTY>

</TARGET>

            <METRIC>ExactMatch(x.title,y.title2)</METRIC>

	
	
    <ACCEPTANCE>
        <THRESHOLD>0.80</THRESHOLD>
        <FILE>test.nt</FILE>
       <RELATION>owl:sameAs</RELATION>
    </ACCEPTANCE>
	
    <REVIEW>
        <THRESHOLD>0.78</THRESHOLD>
        <FILE>testR.nt</FILE>
        <RELATION>owl:sameAs</RELATION>
    </REVIEW>

    <OUTPUT>N3</OUTPUT>
</LIMES>

**Comment by Kleanthi** [comment]
Can you please attach it as a file?

**Comment by 90arslan** [comment]
[config.zip](https://github.com/dice-group/LIMES/files/2345107/config.zip)
it works in version 1.0 but not in 1.5. it did not retrieved triples in 1.5

**Comment by 90arslan** [comment]
[config.zip](https://github.com/dice-group/LIMES/files/2345143/config.zip)
sorry in first file some prefix are missing

**Comment by Kleanthi** [comment]
I wasn't able to reproduce the issue. I think it was a problem of the endpoint itself.
