### ISSUE TITLE
Some ML-configurations of the EAGLE-algorithm don't work

### ISSUE THREAD

**Issue by XLexxaX** [dice-group/LIMES#184]
I am working on an entity-linking task and want to map two datasets with the EAGLE-algorithm. When I try to configure the algorithm, e.g. properties like "generations" or "population" according to http://dice-group.github.io/LIMES/user_manual/configuration_file/defining_ml_tasks.html, I get type conversion issues.

Here are the error message, my configuration and sample input files:
[files.zip](https://github.com/dice-group/LIMES/files/2363255/files.zip)

It would be really nice if you could have a look at this. Pls let me know in case you find anything.

**Comment by Kleanthi** [comment]
hi, based on your attachment, you are trying to pass an string value as integer.  For example the value "199g" is not a valid integer value in Java. This is goes beyond the scope of LIMES, it's a java conversion issue.
