### ISSUE TITLE
Linking task statistics as jason-file

### ISSUE THREAD

**Issue by MSherif** [dice-group/LIMES#185]
Provide the performance indicator (i.e. statistics regarding the linking task) of LIMES as a jason file
something like [sourceDatasetID]_[TargetDataSetID]_statistics.jason 
Note: the statistics is currently available at the end of the configuration file.

**Comment by kvndrsslr** [comment]
Implemented as specified with the additional ability to rename the file using the `-d $file_name` command line option.
