### ISSUE TITLE
can not build LIMES GUI

### ISSUE THREAD

**Issue by wangdsh** [dice-group/LIMES#194]
I can get limes-core/target/limes-core-VERSION-SNAPSHOT.jar. However, when I try to use limes gui, I am in trouble and I can not fix it.<br>
```
limes-gui $ mvn jfx:jar -Dcheckstyle.skip=true -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO] 
[INFO] ----------------------< org.aksw.limes:limes-gui >----------------------
[INFO] Building LIMES GUI 1.5.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO] 
[INFO] >>> javafx-maven-plugin:8.8.3:jar (default-cli) > [jfxjar]package @ limes-gui >>>
Downloading from maven.aksw.snapshots: http://maven.aksw.org/archiva/repository/snapshots/org/aksw/limes/limes-core/1.5.5-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.aksw.limes:limes-core:1.5.5-SNAPSHOT/maven-metadata.xml from/to maven.aksw.snapshots (http://maven.aksw.org/archiva/repository/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.aksw.limes:limes-core:1.5.5-SNAPSHOT/maven-metadata.xml from http://maven.aksw.org/archiva/repository/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of maven.aksw.snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.aksw.limes:limes-core:1.5.5-SNAPSHOT/maven-metadata.xml from/to maven.aksw.snapshots (http://maven.aksw.org/archiva/repository/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Downloading from maven.aksw.snapshots: http://maven.aksw.org/archiva/repository/snapshots/org/aksw/limes/limes-core/1.5.5-SNAPSHOT/limes-core-1.5.5-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.191 s
[INFO] Finished at: 2019-01-16T20:46:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project limes-gui: Could not resolve dependencies for project org.aksw.limes:limes-gui:jar:1.5.5-SNAPSHOT: Failed to collect dependencies at org.aksw.limes:limes-core:jar:1.5.5-SNAPSHOT: Failed to read artifact descriptor for org.aksw.limes:limes-core:jar:1.5.5-SNAPSHOT: Could not transfer artifact org.aksw.limes:limes-core:pom:1.5.5-SNAPSHOT from/to maven.aksw.snapshots (http://maven.aksw.org/archiva/repository/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
I try to solve this problem but failed. Anyone can give me some help? Thanks.

**Comment by wangdsh** [comment]
```
$ mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_91, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by BonaBeavis** [comment]
Try to build the parent project: limes-full.

**Comment by eliohb** [comment]
hello i try to run the command line mvn clean install i got the following error:
[INFO] LIMES .............................................. SUCCESS [  2.786 s]
[INFO] LIMES .............................................. FAILURE [15:14 min]
[INFO] LIMES GUI .......................................... SKIPPED
[INFO] limes-debian-cli ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:17 min
[INFO] Finished at: 2019-02-26T22:21:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project limes-core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Toshiba\Desktop\LIMES-master\limes-core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :limes-core

any advice

**Comment by eliohb** [comment]
hello i try the GUI by running the following command but i got the following error
C:\Users\Toshiba\Desktop\LIMES-master>cd limes-gui

C:\Users\Toshiba\Desktop\LIMES-master\limes-gui>mvn jfx:jar -Dcheckstyle.skip=true -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]
[INFO] ----------------------< org.aksw.limes:limes-gui >----------------------
[INFO] Building LIMES GUI 1.5.6-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]
[INFO] >>> javafx-maven-plugin:8.8.3:jar (default-cli) > [jfxjar]package @ limes-gui >>>
[WARNING] The POM for org.aksw.limes:limes-core:jar:1.5.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.621 s
[INFO] Finished at: 2019-02-26T23:01:34+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project limes-gui: Could not resolve dependencies for project org.aksw.limes:limes-gui:jar:1.5.6-SNAPSHOT: Failure to find org.aksw.limes:limes-core:jar:1.5.6-SNAPSHOT in http://maven.aksw.org/archiva/repository/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of maven.aksw.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
any advice

**Comment by eliohb** [comment]
i have try to run the GUI but i received the following error:
C:\Users\Toshiba\Desktop\LIMES-master>cd limes-gui

C:\Users\Toshiba\Desktop\LIMES-master\limes-gui>mvn jfx:jar -Dcheckstyle.skip=true -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]
[INFO] ----------------------< org.aksw.limes:limes-gui >----------------------
[INFO] Building LIMES GUI 1.5.6-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]
[INFO] >>> javafx-maven-plugin:8.8.3:jar (default-cli) > [jfxjar]package @ limes-gui >>>
[WARNING] The POM for org.aksw.limes:limes-core:jar:1.5.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.621 s
[INFO] Finished at: 2019-02-26T23:01:34+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project limes-gui: Could not resolve dependencies for project org.aksw.limes:limes-gui:jar:1.5.6-SNAPSHOT: Failure to find org.aksw.limes:limes-core:jar:1.5.6-SNAPSHOT in http://maven.aksw.org/archiva/repository/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of maven.aksw.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

any advice

**Comment by wangdsh** [comment]
I did not run "mvn clean install", I ran command "mvn clean package shade:shade -Dcheckstyle.skip=true -Dmaven.test.skip=true" instead, please have a try.

**Comment by eliohb** [comment]
@wangdsh I ran command "mvn clean package shade:shade -Dcheckstyle.skip=true -Dmaven.test.skip=true" and it work but what to do next. Well i am trying to run the GUI by running the command I ran command "mvn jfx:jar -Dcheckstyle.skip=true -Dmaven.test.skip=true" but the follwong error appears any advice:
[WARNING] The POM for org.aksw.limes:limes-core:jar:1.5.6-SNAPSHOT is missing, n
o dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.634 s
[INFO] Finished at: 2019-02-27T11:04:14+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project limes-gui: Could not resolve dependenc
ies for project org.aksw.limes:limes-gui:jar:1.5.6-SNAPSHOT: Failure to find org
.aksw.limes:limes-core:jar:1.5.6-SNAPSHOT in http://maven.aksw.org/archiva/repos
itory/snapshots was cached in the local repository, resolution will not be reatt
empted until the update interval of maven.aksw.snapshots has elapsed or updates
are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by wangdsh** [comment]
the jar file can be used, but the gui can not be used.<br> i can not build gui, either.<br> sorry for no advice.

**Comment by helenxu** [comment]
I

> I can get limes-core/target/limes-core-VERSION-SNAPSHOT.jar. However, when I try to use limes gui, I am in trouble and I can not fix it.
> 
> ```
> limes-gui $ mvn jfx:jar -Dcheckstyle.skip=true -Dmaven.test.skip=true
> [INFO] Scanning for projects...
> [WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
> [WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
> [INFO] 
> [INFO] ----------------------< org.aksw.limes:limes-gui >----------------------
> [INFO] Building LIMES GUI 1.5.5-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
> [WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
> [INFO] 
> [INFO] >>> javafx-maven-plugin:8.8.3:jar (default-cli) > [jfxjar]package @ limes-gui >>>
> Downloading from maven.aksw.snapshots: http://maven.aksw.org/archiva/repository/snapshots/org/aksw/limes/limes-core/1.5.5-SNAPSHOT/maven-metadata.xml
> [WARNING] Could not transfer metadata org.aksw.limes:limes-core:1.5.5-SNAPSHOT/maven-metadata.xml from/to maven.aksw.snapshots (http://maven.aksw.org/archiva/repository/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> [WARNING] Failure to transfer org.aksw.limes:limes-core:1.5.5-SNAPSHOT/maven-metadata.xml from http://maven.aksw.org/archiva/repository/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of maven.aksw.snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.aksw.limes:limes-core:1.5.5-SNAPSHOT/maven-metadata.xml from/to maven.aksw.snapshots (http://maven.aksw.org/archiva/repository/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> Downloading from maven.aksw.snapshots: http://maven.aksw.org/archiva/repository/snapshots/org/aksw/limes/limes-core/1.5.5-SNAPSHOT/limes-core-1.5.5-SNAPSHOT.pom
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 4.191 s
> [INFO] Finished at: 2019-01-16T20:46:35+08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project limes-gui: Could not resolve dependencies for project org.aksw.limes:limes-gui:jar:1.5.5-SNAPSHOT: Failed to collect dependencies at org.aksw.limes:limes-core:jar:1.5.5-SNAPSHOT: Failed to read artifact descriptor for org.aksw.limes:limes-core:jar:1.5.5-SNAPSHOT: Could not transfer artifact org.aksw.limes:limes-core:pom:1.5.5-SNAPSHOT from/to maven.aksw.snapshots (http://maven.aksw.org/archiva/repository/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> ```
> I try to solve this problem but failed. Anyone can give me some help? Thanks.

I encountered the same problem with you. Have you fixed it?

**Comment by wangdsh** [comment]
not yet

**Comment by wttang-bj** [comment]
> not yet

I can't build core neither, by using default repository "http://repo1.maven.org/ "...
Got below error:
[ERROR] Failed to execute goal on project limes-core: Could not resolve dependencies for project org.aksw.limes:limes-core:jar:1.5.8-SNAPSHOT: The following artifacts could not be resolved: algorithms.edjoin:edjoin-plus:jar:2011, uk.ac.shef.wit:simmetrics:jar:1.6.2, jgraphx:jgraphx:jar:1.0, ssjoin:ssjoin:jar:1.0, fr.ign.cogit:geoxygene-api:jar:1.6, fr.ign.cogit:geoxygene-spatial:jar:1.6: Could not find artifact algorithms.edjoin:edjoin-plus:jar:2011 in tbmirror-all (http://repo1.maven.org/maven2) -> [Help 1]

Did you use any additional rep?

Thx

**Comment by Kleanthi** [comment]
Please try the following:

Completely delete your current cloned LIMES folder.
Create a new folder in another location, open the terminal from inside this folder, clone the whole LIMES project using "git clone https://github.com/dice-group/LIMES.git", do "cd LIMES", and execute the commands:

- mvn clean install
- mvn clean package shade:shade -Dcheckstyle.skip=true -Dmaven.test.skip=true
- cd limes-gui
- mvn jfx:jar -Dcheckstyle.skip=true -Dmaven.test.skip=true

It should work now.

**Comment by MSherif** [comment]
Please try to use our new web UI http://limes.aksw.org/
