### ISSUE TITLE
Trigrams similarity strange results

### ISSUE THREAD

**Issue by kvndrsslr** [dice-group/LIMES#195]
The string pair `"Impasto Pizza & Cafe",  "Mpoukia & Sychorio"` has a high similarity value for trigrams but it should not. Need to investigate.

**Comment by abdullahfathi** [comment]
I have created a Unit Test Case and the `Trigram` similarity between the above mentioned strings equals 0.05 which is very small and reflects the high dissimilarity between these strings. See `https://github.com/dice-group/LIMES/tree/hotfix `.
