### ISSUE TITLE
LIMES GUI build error 

### ISSUE THREAD

**Issue by helenxu** [dice-group/LIMES#201]
I tried "mvn jfx:jar -Dcheckstype=true -Dmaven.test.skip=true" but got the following error, can anyone help?

[INFO] 
[INFO] ----------------------< org.aksw.limes:limes-gui >----------------------
[INFO] Building LIMES GUI 1.5.7-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1: Plugin com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.1 or one of its dependencies could not be resolved: Failure to find com.amashchenko.maven.plugin:gitflow-maven-plugin:jar:1.5.1 in http://maven.oa.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO] 
[INFO] >>> javafx-maven-plugin:8.8.3:jar (default-cli) > [jfxjar]package @ limes-gui >>>
[WARNING] The POM for org.aksw.limes:limes-core:jar:1.5.7-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.251 s
[INFO] Finished at: 2019-03-01T15:12:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project limes-gui: Could not resolve dependencies for project org.aksw.limes:limes-gui:jar:1.5.7-SNAPSHOT: Failure to find org.aksw.limes:limes-core:jar:1.5.7-SNAPSHOT in http://maven.aksw.org/archiva/repository/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of maven.aksw.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Kleanthi** [comment]
Based on this error "Failure to find org.aksw.limes:limes-core:jar:1.5.7-SNAPSHOT in http://maven.aksw.org/archiva/repository/snapshots was cached in the local repository", I suggest you follow the steps in the project description on how to generate a Jar File (Headless) and then switch to the gui folder and try to build LIMES's gui.
