### ISSUE TITLE
Function property is missing for rdf config reader.

### ISSUE THREAD

**Issue by BonaBeavis** [dice-group/LIMES#203]
This does not work:

```ttl
limes:linkedgeodataTOlinkedgeodataTarget
      a       limes:TargetDataset ;
      rdfs:label "osm" ;
      limes:endPoint "./../../datasets/osm/osm.ttl" ;
      limes:variable "?y" ;
      limes:restriction "?y a lgdo:BicycleParking" ;
      limes:pageSize "2000" ;
      limes:type "TURTLE" ;
      limes:property "geo:lat" ;
      limes:property "geo:long" ;
      limes:function "toWktPoint(geo:lat, geo:long) RENAME point" ;
```

**Comment by Kleanthi** [comment]
Hi,
can you be a bit more specific? What error do you get?
Also, what are you trying to do with "limes:function "toWktPoint(geo:lat, geo:long) RENAME point" ?

**Comment by BonaBeavis** [comment]
There is no error, the `limes:function` property is silently ignored. I think because it is missing [here](https://github.com/dice-group/LIMES/blob/master/limes-core/src/main/java/org/aksw/limes/core/io/config/reader/rdf/LIMES.java).

**Comment by Kleanthi** [comment]
As a team we are constantly trying to enhance the capabilities of LIMES. We welcome your feedback and we will look into it in the future.

**Comment by BonaBeavis** [comment]
So with a RDF config, [complex](http://dice-group.github.io/LIMES/user_manual/configuration_file/#data-sources) functions are not supported?

**Comment by Kleanthi** [comment]
What type of error do you get when you use  limes:function "toWktPoint(geo:lat, geo:long) RENAME point" ?
Can you try to use . instead of ; at the end of the above line?

**Comment by BonaBeavis** [comment]
Complex function are not parsed in a RDF config, so the `toWktPoint` function is not executed and the `point` variable is not set. This `null` value is not catched anywhere and the metric compares with `y.point` a `null` value. There are no errors thrown, only no links found.
This is because in the [readKBDescription](https://github.com/dice-group/LIMES/blob/75cbc6c8a5e788ce85a7483fc3b9df4a83801638/limes-core/src/main/java/org/aksw/limes/core/io/config/reader/rdf/RDFConfigurationReader.java#L227) function, complex functions are not set. In contrast to the [XML Reader](https://github.com/dice-group/LIMES/blob/75cbc6c8a5e788ce85a7483fc3b9df4a83801638/limes-core/src/main/java/org/aksw/limes/core/io/config/reader/xml/XMLConfigurationReader.java#L262).

**Comment by Kleanthi** [comment]
So when you use an xml file with exactly the same configuration values, you get links?

**Comment by BonaBeavis** [comment]
Y4es, or try a working rdf config with a `fooProperty`, and add a function like:
```
limes:function "fooProperty RENAME barProperty" ;
```
and use a `barProperty` instead of `fooProperty` in your metric. Should work, but won't.

**Comment by Kleanthi** [comment]
It is missing indeed, we will try to fix it soon. Please use the rdf config file for the moment :)

**Comment by kvndrsslr** [comment]
This has been solved in the last release.
