### ISSUE TITLE
LIMES Web UI Execute button not working

### ISSUE THREAD

**Issue by shakeel26** [dice-group/LIMES#205]
Hello,

I have just installed Limos usinf server from user manual: http://dice-group.github.io/LIMES/user_manual/running_limes.html#server

but GUI is not whowing up,  please see in the screenshot the LIMES Web UI webpage is open but clickin gon excute button does nothing and I cant go the main interface which is given in user manual, Can you please guide me in the regard, either inform how to open that web GUI which is given in user manual under section of using GUI, or how to fix the issue of button execute. Thanks 
![Screenshot from 2019-05-04 15-11-20](https://user-images.githubusercontent.com/45169340/57179516-f8c36380-6e7e-11e9-9025-f18b13f1978e.png)
![Screenshot from 2019-05-04 15-11-23](https://user-images.githubusercontent.com/45169340/57179517-f95bfa00-6e7e-11e9-86e9-72b5bcd52fba.png)

**Comment by 123rabida123** [comment]
Hello,

you found a solution of your problem and thank you

**Comment by alicecaporali** [comment]
Hello,

You use this URL : `http://localhost:8080/?`
remove the `/?`, I think it's will work

**Comment by shakeel26** [comment]
Yes, its working at localhost:8080, I am using command line version, but there is an issue with gui. Thanks anyways
