### ISSUE TITLE
[WEB-UI] Use Pipe Notation for individual Threshold in Operators.

### ISSUE THREAD

**Issue by kdrsslr** [dice-group/LIMES#208]
LIMES evaluates operators in a fashion such that it needs the individual threshold for each argument of the operator. 
Even when this threshold is not set by the user it *must* be supplied or the link specification rendered *invalid*.

Example:
`AND(cosine(s.label, t.label)|0.8, jaccard(s.label, t.label)|0.9)`
The most sensible default value in case the user does not choose one is the current value of the *review threshold*.

**Comment by pskLana** [comment]
Fixed bug, added the current value of the review threshold if the user didn't choose threshold for measure.
