### ISSUE TITLE
mvn clean install 报错

### ISSUE THREAD

**Issue by liuluyeah** [dice-group/LIMES#221]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.641 s
[INFO] Finished at: 2020-01-10T15:08:29+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project limes-core: Could not resolve dependencies for project org.aksw.limes:limes-core:jar:1.7.1-SNAPSHOT: The following artifacts could not be resolved: de.vandermeer:asciitable:jar:0.3.2, org.apache.jena:apache-jena-libs:pom:3.9.0, org.aksw.jena-sparql-api:jena-sparql-api-cache-h2:jar:3.9.0-1, org.aksw.jena-sparql-api:jena-sparql-api-core:jar:3.9.0-1, org.apache.jena:jena-core:jar:3.9.0, org.apache.jena:jena-arq:jar:3.9.0, org.locationtech.jts:jts-core:jar:1.16.0, algorithms.edjoin:edjoin-plus:jar:2011, uk.ac.shef.wit:simmetrics:jar:1.6.2, ssjoin:ssjoin:jar:1.0, fr.ign.cogit:geoxygene-api:jar:1.6, fr.ign.cogit:geoxygene-spatial:jar:1.6, net.sf.jgap:jgap:jar:3.4.4, nz.ac.waikato.cms.weka:weka-dev:jar:3.9.0, com.sparkjava:spark-core:jar:2.8.0: Failure to find de.vandermeer:asciitable:jar:0.3.2 in http://10.62.233.85:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of honor has elapsed or updates are forced -> [Help 1]

**Comment by Kleanthi** [comment]
hi! Can you try to clean your mvn folder and then try to run LIMES again?

**Comment by kvndrsslr** [comment]
This is a maven issue that is caused by local misconfiguration and does not belong here, hence closed.
