### ISSUE TITLE
HTTP call not allowed on HTTPS site

### ISSUE THREAD

**Issue by kvndrsslr** [dice-group/LIMES#222]
Due to same-origin access policies established in browsers, HTTP calls must not be made from HTTPS sites. Since we are serving the LIMES demo over HTTPS, all calls should be to HTTPS too.
Please change all requests to `http://prefix.cc` to `https://prefix.cc`, thanks!

**Comment by pskLana** [comment]
Fixed in commit 44b04b2 .
