### ISSUE TITLE
issue in linking file with limes

### ISSUE THREAD

**Issue by i6232834** [dice-group/LIMES#226]
hello. I am trying to link the file through limes. 
i made the rdf file and then make the output file.nt.
i am trying to make the linking part now but getting this error.
![Capture](https://user-images.githubusercontent.com/61944356/76692471-84894d00-6657-11ea-9790-da893b1b17a1.PNG).....

I want to know that i uploaded the .nt files which is the output of rdf file. should i upload the .nt files  which i got from cmd to graph db or the linked file which i got from limes the .json file have to upload on graph db which one.

Kindly reply me as soon as possible

**Comment by Kleanthi** [comment]
Let's find a solution step-by-step. The first issue that both source and target datasets do not include any triples. Please check if the properties you define in the configuration file are present within the graph you want to get the triples from.

**Comment by kvndrsslr** [comment]
Closing as this has become stale.
