### ISSUE TITLE
user doc installation markup broken

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES#231]
In http://dice-group.github.io/LIMES/#/getting_started/installation, there is the line:

> After a successful installation, a target directory should have been created containing the limes-core-c194a9eg<!-- begin-inline-katex{version}-SNAPSHOT.jar (version depending on POM configuration).

I suppose this is markup showing through that is supposed to drop in the version number.

**Comment by kvndrsslr** [comment]
Thanks, fixed that.
