### ISSUE TITLE
Error in Jaccard measure for strings

### ISSUE THREAD

**Issue by alessandro-russo** [dice-group/LIMES#242]
Hi all,

in the Jaccard measure for strings, the similarity computed from `overlap`, `lengthA` and `lengthB` (see [here](https://github.com/dice-group/LIMES/blob/5d2c4d2e379ec1afd2a1cc877e25172be674d119/limes-core/src/main/java/org/aksw/limes/core/measures/measure/string/JaccardMeasure.java#L67-L69)) is currently:
```
overlap / (lengthA + lengthA - overlap)
```
I guess `lengthA` is erroneously used twice; the similarity should be:
```
overlap / (lengthA + lengthB - overlap)
```

Thanks!

**Comment by kvndrsslr** [comment]
Thanks for reporting this

**Comment by abdullahfathi** [comment]
Thanks for reporting this. I have already fixed. See `https://github.com/dice-group/LIMES/tree/hotfix `.
