### ISSUE TITLE
The last version of LIMES generates bad sameAs predicates

### ISSUE THREAD

**Issue by pskLana** [dice-group/LIMES#249]
The last version of LIMES https://github.com/dice-group/LIMES/releases/tag/1.7.5 generates bad sameAs predicates:
```
http://www.w3.org/2011/http#//www.w3.org/2002/07/owl#sameAs.
```
Happens with the following predicates:
```
<PREFIX>
    <NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
    <LABEL>owl</LABEL>
</PREFIX>
<PREFIX>
    <NAMESPACE>http://www.w3.org/2011/http#</NAMESPACE>
    <LABEL>http</LABEL>
</PREFIX>

**Comment by MSherif** [comment]
Do you rally need to define a prefix for `http`?

**Comment by abdullahfathi** [comment]
The reason is that you defined a prefix for HTTP so you got this because the  `HTTP` of `SameAs` will be substituted by the `HTTP` label you defined. 
```

<PREFIX>
    <NAMESPACE>http://www.w3.org/2011/http#</NAMESPACE>
    <LABEL>http</LABEL>
</PREFIX>
```
