### ISSUE TITLE
Inconsistent behaviour of TYPE value

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES#282]
Citing @Aklakan from https://github.com/dice-group/LIMES/pull/273#event-6185065639:

* If no TYPE is given, it is equivalent to <TYPE>sparql</TYPE> and the SparqlQueryModule is used
* When specifying TYPE with no value <TYPE></TYPE> then the ResilientSparqlQueryModule is used.

**Comment by abdullahfathi** [comment]
Fixed
