### ISSUE TITLE
Add CHANGELOG file

### ISSUE THREAD

**Issue by yamalight** [dice-group/LIMES#33]
We need a CHANGELOG.md file that'll describe changes in new builds/releases.
It's possible to use something like [git-extras](https://github.com/tj/git-extras) to generate it, but we need a nice commit messages to do so.

**Comment by Kleanthi** [comment]
Already exists, but not updated.
Now it's up-to-date.

**Comment by yamalight** [comment]
@Kleanthi I think the formatting is a bit off in it
