### ISSUE TITLE
Instance.getProperty() odd behaviour

### ISSUE THREAD

**Issue by kvndrsslr-zz** [dice-group/LIMES#60]
In Java, collection classes normally return null if a requested field can't be found.
Instead of this default and well known behaviour, org.aksw.limes.core.io.cache.Instance emits a disruptive warning message and returns an empty TreeSet. 
This should be resolved and existing usages that rely on the the empty TreeSet should be updated.

**Comment by kvndrsslr** [comment]
This will be resolved when refactoring Caches API in v2
