### ISSUE TITLE
ML Implementations not able to learn temporal measures

### ISSUE THREAD

**Issue by kvndrsslr-zz** [dice-group/LIMES#77]
- temporal measures use non-standard atomic LS, e.g. `tmp_during(x.birth|death,y.birth|death)`
- machine learning assembles atomic LS according to standardized syntax (2 properties)
- AllenAlgebraMatcher fails for these assembled LS
- need to come up with an standardized extension to measures package & LS syntax
  - measures should be able to expose the way they expect an atomic LS to look like
  - measures also should provide a validator for incoming data, e.g. temporal measures expects dates in a certain format, spatial relation measures expect geometries to be in WKT format, but currently we do not communicate this well to the user and violation leads to exceptions that are hard to trace for non-core devs.
  - in turn ML algorithms could profit from these enhancements, as they would be able to infer which properties are best suited for a given measure (we all love semantics, right?)

**Comment by kvndrsslr** [comment]
This will be taken into account in the LIMES 2 LS redesign
