### ISSUE TITLE
Wombat complete and Eagle

### ISSUE THREAD

**Issue by ziqizhang** [dice-group/LIMES#94]
Hi again

I have managed to use 'wombat simple' and now I would like to try 'wombat complete' and 'eagle' algorithms. I came across problems with both.

I noticed that currently wombat complete is disabled, as per line 34 of `org.aksw.limes.core.ml.algorithm.MLAlgorithmFactory`:

` if (name.equalsIgnoreCase(WOMBAT_COMPLETE)) {`
 `           //@todo: fix this`
`            return null;`
 `       }`

**Is there a newer version where I can use wombat complete?**

Then I tried Eagle with the following config, with all other config details being identical to a wombat simple setting that works:

`<MLALGORITHM>`
    `    	<NAME>eagle</NAME>`
	`        <TYPE>supervised batch</TYPE>`
	`<TRAINING>/home/zqz/Work/scholarlydata/data/limes_experiment/org_1_training_3quarters_pos.nt</TRAINING>`
	       `		<PARAMETER> `
        `	    <NAME>max_duration</NAME>`
`	            <VALUE>600</VALUE>`
 `       	</PARAMETER>`
`	</MLALGORITHM>`

, but then a `nullpointerexception` was thrown, because in line 221 of `org.aksw.limes.core.ml.algorithm.ACoreMLAlgorithm`:

`LinkSpecGeneticLearnerConfig jgapConfig = new LinkSpecGeneticLearnerConfig(getConfiguration().getSourceInfo(), getConfiguration().getTargetInfo(), pm);
`

**the method `getConfiguration()` returns null.**

Any suggestions please?

Thanks

**Comment by mommi84** [comment]
Hi! I can answer for Eagle.
Can you please provide me with the full stack trace?

**Comment by ziqizhang** [comment]
Hi, thanks.

The full config is also here: https://drive.google.com/file/d/0BwMotMkSrggXTFhGYVRiN2JxcGM/view?usp=sharing

`13:35:28.900 [main] INFO  org.aksw.limes.core.io.config.reader.rdf.RDFConfigurationReader - Opening N-Triples file`
`13:35:28.948 [main] INFO  org.aksw.limes.core.io.config.reader.rdf.RDFConfigurationReader - Loading /home/zqz/Work/scholarlydata/data/limes_experiment/org_4_training_3quarters_pos.nt is done in 747ms.`
`13:35:28.967 [main] INFO  org.aksw.limes.core.ml.algorithm.Eagle - Setting up EAGLE...`
`Exception in thread "main" java.lang.NullPointerException`
`	at org.aksw.limes.core.ml.algorithm.Eagle.setUp(Eagle.java:221)`
`	at org.aksw.limes.core.ml.algorithm.Eagle.learn(Eagle.java:105)`
`	at org.aksw.limes.core.ml.algorithm.SupervisedMLAlgorithm.learn(SupervisedMLAlgorithm.java:42)`
`	at org.aksw.limes.core.controller.MLPipeline.execute(MLPipeline.java:60)`
`	at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:147)`
`	at org.aksw.limes.core.controller.Controller.main(Controller.java:75)`
`	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
`	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`	at java.lang.reflect.Method.invoke(Method.java:498)`
`	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

**Comment by kvndrsslr** [comment]
Although **Wombat Complete** got activated in the dev branch, we are currently investigating a discovered bug within it. You probably want to wait for us finishing this, to be sure that it works the way it is intended. We'll try to have it running by tomorrow.

**Comment by ziqizhang** [comment]
Thanks guys, i ll wait till the end of tommorrow.

**Comment by kvndrsslr** [comment]
After our investigations, we found that wombat complete in its current state is **correct**. However, one of the default measures it uses, **trigrams** has an issue that it is **not complete** at the moment. I will come back to fixing those things this evening or tomorrow.
Right now, if your data is mostly strings, I would suggest you configure Wombat Complete to just use the **jaro** or **jarowinkler** measures. They currently work best with the Wombat implementation (which we will streamline and optimize further as a result of the current investigations, so thank you for your feedback).

**Comment by ziqizhang** [comment]
thanks, that is not a problem. My data are all multi-valued properties, so I am using set jaccard.

**Comment by MSherif** [comment]
@kvndrsslr please check if there is something still to be done with this issue, other wise close it.
