### ISSUE TITLE
Trigrams Mapper is not complete w.r.t. Trigrams Measure

### ISSUE THREAD

**Issue by kvndrsslr** [dice-group/LIMES#96]
For input strings `String s="Werner"; String t="Wernre"`, the Measure returns the correct similarity  of `0.666...`. However, using the Mapper on this example with threshold set to 0.65 returns an empty Mapping.

**Comment by Kleanthi** [comment]
Trigrams mapper is PPJoinPlusPlus?

**Comment by Kleanthi** [comment]
PPJoinPlusPlus acts differently when there are more than 2 instances to compare. It's a problem of the mapper. So, we need to do a major revision to the mapper itself.
