### ISSUE TITLE
Refactor GUI code into another Maven module

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES#97]
I suggest discussing to separate the core/command line and the GUI part into separate maven modules. While this adds another step to the installation, it avoids the JavaFX issue (which may be hard to fix with some operating systems and some people don't have admin rights to their work PCs). This also makes it easier to add different GUIs in the future. Alternatively, I suggest uploading the jar files to the releases so that people don't have to compile it themselves. As long as they don't run the GUI code, it may be possible that they don't need the JavaFX libraries then.

**Comment by mwauer** [comment]
Good point, +1 from me.

**Comment by dobraczka** [comment]
I've made an attempt for this in [this branch](https://github.com/AKSW/LIMES-dev/tree/feature/maven-multimodule)

**Comment by KonradHoeffner** [comment]
Great! However I would rename the folder name from "GUI" and the artifact name from "limes-GUI" both to "limes-gui", to have a consistent naming scheme. Also, the parent pom could be extended with dependency versions for those that are used in both modules.
